#!/bin/sh

apt-get update
apt-get upgrade
apt-get install apache2
apt-get install rrdtool
apt-get install python-dev python-pip python-rrdtool
apt-get install libavahi-compat-libdnssd-dev
wget -O /var/tmp/node_latest_armhf.deb http://node-arm.herokuapp.com/node_latest_armhf.deb
dpkg -i /var/tmp/node_latest_armhf.deb

