#! /bin/sh

### BEGIN INIT INFO
# Provides:	        pi-go-homekit
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	Smart PoolPump Functionality
### END INIT INFO

set -e

# /etc/init.d/poold: start and stop the poold daemon
name='pi-go-homekit'
conf='/etc/poold.conf'
bin="/usr/local/bin/$name"
rundir="/var/run/$name"
pidfile="/tmp/$name.pid"

test -x $bin || exit 0
umask 022
export PATH="${PATH:+$PATH:}/usr/local/bin"

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_data_dir() {
    # Create the Data empty dir if necessary
    if [ ! -d $rundir ]; then
	mkdir $rundir
	chmod 0755 $rundir
    fi
}

start() {
    check_data_dir
    cd $rundir
    $bin $conf &
}

stop_daemon() {
    log_daemon_msg "Stopping server" $bin || true
    if pkill -9 $name; then
	log_end_msg 0 || true
    else
	log_end_msg 1 || true
    fi
}


case "$1" in
    start)
	start
	;;
    stop)
	stop_daemon
	;;

    restart)
	stop_daemon
	start_daemon
	;;

    status)
	status_of_proc -p $pid $bin && exit 0 || exit $?
	;;

    *)
	log_action_msg "Usage: /etc/init.d/poold {start|stop|restart|status}" || true
	exit 1
esac

exit 0
